# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
app_name: LGApp
release_version: 1.0.17
title: Luke Giuliani
byline: "Social entrepreneur, strategist and technologist"
ga_id: UA-54362665-1
fb_app_id: 1
keywords: "Social Enterprise, Luke Giuliani, Luke, Giuliani, Grace, Squareweave, Fitzroy GSD, "
description: "Passionate about using technology to make the world better, Luke is a social entrepreneur who has started numerous projects and businesses. These include Squareweave, a web company making the world better with technology; Grace, a cafe in Fitzroy; OurSay, a social enterprise connecting citizens to decision makers; and The Fitzroy Academy of Getting Shit Done, a project to teach people how to work on ideas that don’t even exist yet."
ga_domain: ~
team:
    luke: { key: 11, name: Luke Giuliani, role: Founder, image: luke.jpg, url: https://www.linkedin.com/in/lukegiuliani }

work:
    - { url: "https://squareweave.com.au", role: Founder, name: Squareweave, backgroundImage: squareweave-bg.png, image: squareweave.png, imageWidth: 120, imageHeight: 120 }
    - { url: "http://gracefitzroy.com", role: Founder, name: Grace, backgroundImage: grace-bg, image: grace.png, imageWidth: 120, imageHeight: 120 }
    - { url: "http://oursay.org", role: Director, name: OurSay, backgroundImage: oursay-bg.png, image: oursay.png, imageWidth: 150, imageHeight: 110 }
    - { url: "http://fitzroygsd.com/", role: Founder, name: Fitzroy GSD, backgroundImage: gsd-bg, image: gsd.png, imageWidth: 120, imageHeight: 120 }
    - { url: "http://climateforchange.org.au/", role: Chair, name: Climate for Change, backgroundImage: climate-for-change-bg.png, image: climate-for-change.png, imageWidth: 120, imageHeight: 120 }
    - { url: "http://rightnow.org.au/", role: Board member, name: Right Now, backgroundImage: right-now-bg, image: right-now.png, imageWidth: 120, imageHeight: 120 }
    - { url: "https://livebelowtheline.com.au/", role: Board member, name: Live below the line, backgroundImage: live-bellow-bg, image: live-bellow.png, imageWidth: 204, imageHeight: 54 }
    - { url: "http://clarity.io/", role: Founder, name: CTO, backgroundImage: clarity-bg.png, image: clarity.png, imageWidth: 120, imageHeight: 120 }
    - { url: "http://futurespark.com.au/", role: Founder, name: Future Spark, backgroundImage: future-spark-bg, image: future-spark.png, imageWidth: 168, imageHeight: 38 }
    - { url: "http://sideracket.com/", role: CTO, name: Side Racket, backgroundImage: sideracket-bg, image: sideracket.png, imageWidth: 120, imageHeight: 120 }
    - { url: "http://shift.vc/", role: Founder, name: Shift.vc, backgroundImage: shift.png, image: shift.png, imageWidth: 120, imageHeight: 106 }

# add in iawards. 
